name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build Docker flask image
      run: docker build --target flask -t opentransit/flask:latest .
    - name: Run tests
      run: docker run opentransit/flask:latest python -m unittest discover -s tests
